name: test
on: [ push ]
jobs:
  appleos:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
        - 'platform=macOS,arch=x86_64'
        - 'platform=iOS Simulator,OS=latest,name=iPhone 11 Pro'
        - 'platform=tvOS Simulator,OS=latest,name=Apple TV 4K'
    steps:
    - name: Select latest available Xcode
      uses: maxim-lobanov/setup-xcode@1.0
      with: { 'xcode-version': 'latest' }
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests for ${{ matrix.destination }}
      run: xcodebuild test -scheme NetworkClient -enableThreadSanitizer YES -destination '${{ matrix.destination }}'
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner:
        - xenial
        - bionic
    container:
      image: swift:${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests for ${{ matrix.runner }}
      run: swift test --enable-test-discovery --sanitize=thread
